Repository fri-team/Swapify, pull requests merged in 2018-05, with the labels that each got.

#56 Feature/#21 show student timetable
  WebAPI/Controllers/TimetableController.cs
  WebAPI/Models/ErrorMessage.cs
  WebAPI/Models/Timetable.cs
  WebAPI/Models/TimetableBlock.cs
  WebAPI/Models/TimetableBlockType.cs
  WebAPI/Properties/launchSettings.json
  WebAPI/Startup.cs
  WebApp/package-lock.json
  WebApp/package.json
  WebApp/src/actions/blockDetailActions.js
  WebApp/src/actions/timetableActions.js
  WebApp/src/actions/timetableData.json
  WebApp/src/components/App.js
  WebApp/src/components/BlockDetail/BlockDetail.js
  WebApp/src/components/BlockDetail/BlockDetail.scss
  WebApp/src/components/Sidebar/Sidebar.scss
  WebApp/src/components/SvgButton/SvgButton.js
  WebApp/src/components/SvgButton/SvgButton.scss
  WebApp/src/components/Timetable/Timetable.js
  WebApp/src/components/Timetable/Timetable.scss
  WebApp/src/components/Timetable/TimetableBlock.js
  WebApp/src/components/Timetable/TimetableBlock.scss
  WebApp/src/components/Timetable/TimetableBlocks.js
  WebApp/src/components/Timetable/TimetableBlocks.test.js
  WebApp/src/components/svg/Cancel.js
  WebApp/src/components/svg/Delete.js
  WebApp/src/components/svg/Laboratory.js
  WebApp/src/components/svg/Lecture.js
  WebApp/src/components/svg/Location.js
  WebApp/src/components/svg/Person.js
  WebApp/src/components/svg/SwapHorizontal.js
  WebApp/src/constants/actionTypes.js
  WebApp/src/containers/BlockDetailContainer/BlockDetailContainer.js
  WebApp/src/containers/SidebarContainer/SidebarContainer.js
  WebApp/src/containers/TimetableBlockContainer/TimetableBlockContainer.js
  WebApp/src/containers/TimetableContainer/TimetableContainer.js
  WebApp/src/reducers/__test__/hideCourseTimetable.json
  WebApp/src/reducers/__test__/loadCourseTimetableDone.json
  WebApp/src/reducers/__test__/loadMyTimetableDone.json
  WebApp/src/reducers/__test__/mergeTimetables.json
  WebApp/src/reducers/__test__/showCourseTimetable.json
  WebApp/src/reducers/blockDetailReducer.js
  WebApp/src/reducers/blockReducer.js
  WebApp/src/reducers/index.js
  WebApp/src/reducers/timetableReducer.js
  WebApp/src/reducers/timetableReducer.test.js
  WebApp/src/styles/globals.scss
  WebApp/src/styles/styles.scss
Labels: C#, js

#57 Feature/#55 react router
  WebAPI/Controllers/UserController.cs
  WebAPI/Models/RegisterBody.cs
  WebApp/src/components/App.js
  WebApp/src/components/HomePage/HomePage.js
  WebApp/src/components/NotFoundPage/NotFoundPage.js
  WebApp/src/components/NotFoundPage/NotFoundPage.scss
  WebApp/src/components/RegisterPage/RegisterPage.js
  WebApp/src/components/TimetablePage/TimetablePage.js
  WebApp/src/util/stateBinding.js
Labels: C#, js

#52 continual building timetable #51
  APIWrapper/ResponseParser.cs
  Backend/Converter/ConverterApiToDomain.cs
  Backend/CourseService.cs
  Backend/Interfaces/ICourseService.cs
  Backend/StudyGroupService.cs
  Entities/Block.cs
  Entities/Timetable.cs
  Tests/BackendTest/ConverterTest.cs
  Tests/BackendTest/ParserTest.cs
Labels: C#

#62 #42 welcome/home page
  WebApp/src/components/Button/Button.js
  WebApp/src/components/Button/Button.scss
  WebApp/src/components/HomePage/HomePage.js
  WebApp/src/components/HomePage/HomePage.scss
  WebApp/src/images/home-background.png
Labels: EP: Register, design, js
