Repository fri-team/Swapify, pull requests merged in 2018-11, with the labels that each got.

#94 Feature/#27 finish login page
  Backend/EmailService.cs
  Backend/Settings/EnvironmentSettings.cs
  Dockerfile-CI
  Tests/IntegrationTest/IntegrationTest.csproj
  Tests/IntegrationTest/TestFixture.cs
  WebAPI/Controllers/StudentController.cs
  WebAPI/appsettings.json
  WebApp/src/actions/userActions.js
  WebApp/src/components/App.js
  WebApp/src/components/HomePage/HomePage.js
  WebApp/src/components/LoginPage/LoginPage.js
  WebApp/src/components/RegisterPage/RegisterPage.js
  WebApp/src/constants/actionTypes.js
  WebApp/src/index.js
  WebApp/src/reducers/index.js
  WebApp/src/reducers/userReducer.js
  WebApp/src/reducers/userReducer.test.js
  WebApp/src/sagas/index.js
  WebApp/src/sagas/userSagas.js
  WebApp/src/sagas/userSagas.test.js
  WebApp/src/store/configureStore.js
  WebApp/src/util/auth.js
  WebApp/src/util/index.js
  WebApp/src/util/routes.js
  WebApp/src/util/stateBinding.js
Labels: C#, EP: Profile, devops, js

#97 #96 Create DB Seed, log application startup
  Backend/DbSeed/DbSeed.cs
  Backend/Settings/EnvironmentSettings.cs
  Backend/Settings/IdentitySettings.cs
  Backend/Settings/MailingSettings.cs
  Backend/Settings/SettingsBase.cs
  WebAPI/Filters/ValidationFilter.cs
  WebAPI/Program.cs
  WebAPI/Startup.cs
Labels: C#, EP: Register, devops

#98 Feature/#95 logout
  WebAPI/Controllers/UserController.cs
  WebAPI/Models/UserModels/AuthenticatedUserModel.cs
  WebApp/package-lock.json
  WebApp/package.json
  WebApp/src/components/App.js
  WebApp/src/components/BlockDetail/BlockDetail.js
  WebApp/src/components/HamburgerButton/HamburgerButton.js
  WebApp/src/components/HamburgerButton/HamburgerButton.scss
  WebApp/src/components/Root.js
  WebApp/src/components/Sidebar/Sidebar.js
  WebApp/src/components/Sidebar/Sidebar.scss
  WebApp/src/components/Sidebar/SidebarContainer.js
  WebApp/src/components/SvgButton/SvgButton.js
  WebApp/src/components/SvgButton/SvgButton.scss
  WebApp/src/components/Timetable/Timetable.scss
  WebApp/src/components/TimetablePage/TimetablePage.js
  WebApp/src/components/Toolbar/Menu.js
  WebApp/src/components/Toolbar/Toolbar.js
  WebApp/src/components/Toolbar/Toolbar.scss
  WebApp/src/components/Toolbar/UserAvatar.js
  WebApp/src/components/Toolbar/shared.js
  WebApp/src/components/UserButton/UserButton.js
  WebApp/src/components/UserButton/UserButton.scss
  WebApp/src/components/index.js
  WebApp/src/components/svg/Cancel.js
  WebApp/src/components/svg/Delete.js
  WebApp/src/containers/SidebarContainer/SidebarContainer.js
  WebApp/src/reducers/userReducer.js
  WebApp/src/reducers/userReducer.test.js
  WebApp/src/sagas/userSagas.js
  WebApp/src/sagas/userSagas.test.js
  WebApp/src/styles/styles.scss
Labels: js

#100 Bugfix/#99 update vulnerable packages
  APIWrapper/APIWrapper.csproj
  Backend/Backend.csproj
  Backend/Interfaces/IUserService.cs
  Backend/UserService.cs
  Entities/Entities.csproj
  Tests/BackendTest/BackendTest.csproj
  Tests/IntegrationTest/IntegrationTest.csproj
  WebAPI/Controllers/UserController.cs
  WebAPI/Models/UserModels/AuthenticatedUserModel.cs
  WebAPI/Models/UserModels/RenewModel.cs
  WebAPI/WebAPI.csproj
  WebApp/package-lock.json
  WebApp/package.json
  WebApp/src/actions/timetableActions.js
  WebApp/src/actions/userActions.js
  WebApp/src/components/BlockDetail/BlockDetail.js
  WebApp/src/components/Form/Form.js
  WebApp/src/components/LoginPage/LoginPage.js
  WebApp/src/components/RegisterPage/RegisterPage.js
  WebApp/src/components/Sidebar/SidebarContainer.js
  WebApp/src/components/Timetable/Timetable.js
  WebApp/src/components/Timetable/TimetableBlocks.js
  WebApp/src/components/index.js
  WebApp/src/constants/actionTypes.js
  WebApp/src/reducers/timetableReducer.js
  WebApp/src/reducers/userReducer.js
  WebApp/src/sagas/userSagas.js
  WebApp/src/sagas/userSagas.test.js
  WebApp/webpack.config.prod.js
Labels: C#, js

#109 structure, adding, removing and view exchanges #106
  Backend/BlockChangesService.cs
  Backend/Interfaces/IBlockChangesService.cs
  Entities/BlockChangeRequest.cs
  Entities/Enums/ExchangeStatus.cs
  Entities/Student.cs
  Tests/BackendTest/BlockChangeRequestTest.cs
Labels: C#
